### ISSUE TITLE
npm start throws "module.js:540 throw err;"

### ISSUE THREAD

**Issue by patrick-ehs** [cosmicjs/appointment-scheduler#1]
I downloaded the project, ran 'npm i' and then 'npm start' but i keep getting this error.

first on npm -v 5.4.2 node -v **8.9.1**
then on npm -v 5.4.2 node -v **8.9.4**

can anyone help me with this? 

Thanks in advance.

![image](https://user-images.githubusercontent.com/22769396/36205445-165fe358-118f-11e8-88a9-a6c37b56af31.png)

**Comment by jackynguyen93** [comment]
I got the same

**Comment by jamesbaker1** [comment]
Same, anyone have any luck?

**Comment by jamesbaker1** [comment]
Fixed it. It is looking for a development.js file in your config folder that looks like this (but filled out with your respective keys):
`module.exports = {
  bucket: {
    slug: "",
    read_key: "",
    write_key: ""
  },
  twilio: {
    auth: "",
    sid: "",
    number: ""
  }
}
`

**Comment by tonyspiro** [comment]
Thanks for the heads up. Added instructions for this in the README.
